# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("NerveRP Car Injection")
        MainWindow.setWindowIcon(QtGui.QIcon('nerve.ico')) 
        MainWindow.resize(385, 459)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["Click to select a model:", "Ford GT", "Porsche 718 GT4", "Honda NSX", 
        "McLaren GT2020", "Porsche Taycan", "Aston Martin DBS", "Jeep Trackhawk", "Chrysler 300c",
        "Range Rover", "Chevy Suburban", "Mercedes GL63", "Toyota Camry", "C8", "1965 Pontiac GTO",
        "Ford Explorer ST", "EVO 10", "Mercedes G65", "1996 Impala", "Kia Stinger", "Mercedes E63",
        "Hyundai Sonata", "Mercedes SLS AMG", "BMW E39", "Subaru WRX", "1965 Mustang", "BMW M5", "Toyota Prius", "Camaro ZL1",
        "Dodge Ram", "Toyota Tundra", "Audi RS6", "Audi A8", "Dodge Demon", "Maybach S650", "Bentley Super Sport", "1969 Mustang Boss", 
        "Ferrari California", "Jaguar XJS V12", "RX7 Savanna","Koenigsegg Regera", "Mercedes GT 63", "BMW I8", "S65 AMG", "McLaren Senna", 
        "Nissan Skyline R34", "AMG GTS Mansory", "Hellheim Bike"
        ])
        self.comboBox.currentIndexChanged.connect(self.btn_clk)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 120, 201, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 150, 201, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 390, 91, 23))
        self.pushButton.clicked.connect(self.btn_clk)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 90, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(160, 190, 70, 17))
        self.checkBox.stateChanged.connect(self.btn_clk)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 219, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 260, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.primarySpin = QtWidgets.QSpinBox(self.centralwidget)
        self.primarySpin.setGeometry(QtCore.QRect(160, 220, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.primarySpin.setFont(font)
        self.primarySpin.setAccelerated(True)
        self.primarySpin.setMinimum(-1)
        self.primarySpin.setMaximum(159)
        self.primarySpin.setProperty("value", -1)
        self.primarySpin.setObjectName("primarySpin")
        self.primarySpin.valueChanged.connect(self.btn_clk)
        self.secondarySpin = QtWidgets.QSpinBox(self.centralwidget)
        self.secondarySpin.setGeometry(QtCore.QRect(160, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.secondarySpin.setFont(font)
        self.secondarySpin.setAccelerated(True)
        self.secondarySpin.setMinimum(-1)
        self.secondarySpin.setMaximum(159)
        self.secondarySpin.setProperty("value", -1)
        self.secondarySpin.setObjectName("secondarySpin")
        self.secondarySpin.valueChanged.connect(self.btn_clk)
        self.pearlSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.pearlSpin.setGeometry(QtCore.QRect(160, 300, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.pearlSpin.setFont(font)
        self.pearlSpin.setAccelerated(True)
        self.pearlSpin.setMinimum(-1)
        self.pearlSpin.setMaximum(159)
        self.pearlSpin.setProperty("value", -1)
        self.pearlSpin.setObjectName("pearlSpin")
        self.pearlSpin.valueChanged.connect(self.btn_clk)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 385, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NerveRP Car Injection"))
        self.label_2.setText(_translate("MainWindow", "Number Plate:"))
        self.label_3.setText(_translate("MainWindow", "User Licesne:"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.label_4.setText(_translate("MainWindow", "Model (if not selected):"))
        self.checkBox.setText(_translate("MainWindow", "Turbo"))
        self.label_5.setText(_translate("MainWindow", "Primary Colour:"))
        self.label_6.setText(_translate("MainWindow", "Secondary Colour:"))
        self.label_7.setText(_translate("MainWindow", "Pearlescent:"))


    def btn_clk(self, state):
        sql = """
INSERT INTO `owned_vehicles` (`vehicle`, `owner`, `stored`, `garage_name`, `pound`, `vehiclename`, `plate`, `type`, `job`, `tunerdata`, `garage_type`, `garage_id`, `in_garage`, `impound`, `adv_stats`, `property`) VALUES
	('{"model":modelNum,"modDoorSpeaker":-1,"modXenon":false,"modHorns":-1,"modStruts":-1,"modRoof":-1,"engineHealth":967.6,"modSuspension":-1,"modAirFilter":-1,"tankHealth":999.9,"xenonColor":255,"modTurbo":hasTurbo,"plateIndex":1,"modTrunk":-1,"modTrimB":-1,"modSteeringWheel":-1,"color1":primColour,"modRearBumper":-1,"modSideSkirt":-1,"modFrontBumper":-1,"modBrakes":-1,"tyreSmokeColor":[255,255,255],"modShifterLeavers":-1,"color2":secColour,"modAPlate":-1,"modTrimA":-1,"modExhaust":-1,"bodyHealth":997.0,"modAerials":-1,"modOrnaments":-1,"modSpoilers":-1,"wheels":2,"modEngineBlock":-1,"modArmor":-1,"modRightFender":-1,"extras":{"1":false},"modSpeakers":-1,"modGrille":-1,"modBackWheels":-1,"modWindows":-1,"dirtLevel":0.0,"modFrame":-1,"modArchCover":-1,"neonEnabled":[false,false,false,false],"modDashboard":-1,"modDial":-1,"modLivery":-1,"pearlescentColor":pearlColour,"modFender":-1,"modEngine":-1,"tyres":[false,false,false,false,false,false,false],"fuelLevel":30.3,"modHydrolic":-1,"modTank":-1,"modTransmission":-1,"doors":[false,false,false,false,false,false],"windowTint":-1,"modHood":-1,"neonColor":[255,0,255],"modSeats":-1,"modFrontWheels":-1,"plate":"plateFirst","wheelColor":156,"modSmokeEnabled":false,"modPlateHolder":-1,"modVanityPlate":-1}', 'LICENSE', 1, 'Garage_Centre', 0, NULL, 'plateSecond', 'car', NULL, '', 'car', 'Legion', 1, 0, '{"maxhealth":1000.0,"plate":"nil","mileage":0.21256766319274904}', 0)
"""     
        

        output = self.comboBox.currentText()
        if output == "Ford GT":
            modelVal = "-2011325074"
        elif output == "Porsche 718 GT4":
            modelVal = "1067974426"
        elif output == "Honda NSX":
            modelVal = "-378442770"
        elif output == "McLaren GT2020":
            modelVal = "1082938645"
        elif output == "Porsche Taycan":
            modelVal = "1502692741"
        elif output == "Aston Martin DBS":
            modelVal = "1720228960"
        elif output == "Jeep Trackhawk":
            modelVal = "-1003581048"
        elif output == "Chrysler 300c":
            modelVal = "-1249987689"
        elif output == "Range Rover":
            modelVal = "1993609528"
        elif output == "Chevy Suburban":
            modelVal = "-701263831"
        elif output == "Mercedes GL63":
            modelVal = "1382221388"
        elif output == "Toyota Camry":
            modelVal = "-1990645087"
            ########################
        elif output == "C8":
            modelVal = "-1150515393"
        elif output == "1965 Pontiac GTO":
            modelVal = "-642122035"
        elif output == "Ford Explorer ST":
            modelVal = "-1796933658"
        elif output == "EVO 10":
            modelVal = "1944777953"
        elif output == "Mercedes G65":
            modelVal = "104532066"
        elif output == "1996 Impala":
            modelVal = "-1055429929"
        elif output == "Kia Stinger":
            modelVal = "-1962234663"
        elif output == "Mercedes E63":
            modelVal = "-662904049"
        elif output == "Hyundai Sonata":
            modelVal = "-1619632315"
        elif output == "Mercedes SLS AMG":
            modelVal = "2093958905"
            ##############
        elif output == "BMW E39":
            modelVal = "1026616240"
        elif output == "Subaru WRX":
            modelVal = "-1298373790"
        elif output == "1965 Mustang":
            modelVal = "-1567919678"
        elif output == "BMW M5":
            modelVal = "1093697054"
        elif output == "Toyota Prius":
            modelVal = "1418132356"
        elif output == "Camaro ZL1":
            modelVal = "531756283"
        elif output == "Dodge Ram":
            modelVal = "-608300537"
        elif output == "Toyota Tundra":
            modelVal = "-420359219"
        elif output == "Audi RS6":
            modelVal = "-134949878"
        elif output == "Audi A8":
            modelVal = "-235523255"
        elif output == "Dodge Demon":
            modelVal = "885421525"
        ###########################
        elif output == "Maybach S650":
            modelVal = "1056539313"
        elif output == "Bentley Super Sport":
            modelVal = "-2049278303"
        elif output == "1969 Mustang Boss":
            modelVal = "-368114364"
        elif output == "Ferrari California":
            modelVal = "-784906648"
        elif output == "Jaguar XJS V12":
            modelVal = "1993373021"
        elif output == "RX7 Savanna":
            modelVal = "1675614131"
        elif output == "Koenigsegg Regera":
            modelVal = "1085789913"
        elif output == "Mercedes GT 63":
            modelVal = "980885719"
        elif output == "BMW I8":
            modelVal = "176791999"
        elif output == "S65 AMG":
            modelVal = "33105597"
        elif output == "McLaren Senna":
            modelVal = "-433961724"
        elif output == "Nissan Skyline R34":
            modelVal = "2117711508"
        elif output == "AMG GTS Mansory":
            modelVal = "1909252846"
        elif output == "Hellheim Bike":
            modelVal = "1902511494"
        else:
            modelVal = self.lineEdit_3.text()

        numPlate = self.lineEdit.text() #number plate
        
        if self.checkBox.isChecked():
            isTurbo = "true"
        else:
            isTurbo = "false"
        
        if self.primarySpin.value() == -1:
            primColour = "0"
        else:
            primColour = self.primarySpin.value()

        if self.secondarySpin.value() == -1:
            secColour = "0"
        else:
            secColour = self.secondarySpin.value()

        if self.pearlSpin.value() == -1:
            pearlColour = "0"
        else:
            pearlColour = self.pearlSpin.value()
        
        userLicense = self.lineEdit_2.text() # license

        changedModel = sql.replace("modelNum", str(modelVal))
        changedPlateFirst = changedModel.replace("plateFirst", str(numPlate))
        changedPlateSecond = changedPlateFirst.replace("plateSecond", str(numPlate))
        changedLicense = changedPlateSecond.replace("LICENSE", str(userLicense))
        changedTurbo = changedLicense.replace("hasTurbo", str(isTurbo))
        changedPrimary = changedTurbo.replace("primColour", str(primColour))
        changedSecondary = changedPrimary.replace("secColour", str(secColour))
        changedPearl = changedSecondary.replace("pearlColour", str(pearlColour))
        

        now = datetime.now()

        dt_string = now.strftime("%d%m%Y-%H%M")

        while userLicense != "":
            text_file = open(dt_string + ".sql", "w")
            text_file.write(changedPearl)
            text_file.close()
            break


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
